-- =============================================
-- CompareBuddy: Car Seed Data (Thailand Market)
-- =============================================

-- BRANDS (15)
INSERT INTO car_brands (name, name_th, country) VALUES
('BYD', 'บีวายดี', 'China'),
('Tesla', 'เทสลา', 'USA'),
('MG', 'เอ็มจี', 'China/UK'),
('ORA', 'โอร่า', 'China'),
('Neta', 'เนต้า', 'China'),
('Toyota', 'โตโยต้า', 'Japan'),
('Honda', 'ฮอนด้า', 'Japan'),
('Hyundai', 'ฮุนได', 'South Korea'),
('Mercedes-Benz', 'เมอร์เซเดส-เบนซ์', 'Germany'),
('BMW', 'บีเอ็มดับเบิลยู', 'Germany'),
('Volvo', 'วอลโว่', 'Sweden'),
('AION', 'ไอออน', 'China'),
('Changan', 'ฉางอัน', 'China'),
('Deepal', 'ดีพอล', 'China'),
('Nissan', 'นิสสัน', 'Japan');

-- MODELS
INSERT INTO car_models (brand_id, name, powertrain_type, body_type, segment, year_launched, status) VALUES
-- BYD (brand_id=1)
(1, 'Atto 3', 'BEV', 'suv', 'c', 2022, 'on_sale'),
(1, 'Dolphin', 'BEV', 'hatchback', 'b', 2023, 'on_sale'),
(1, 'Seal', 'BEV', 'sedan', 'c', 2023, 'on_sale'),
(1, 'Sealion 6 DM-i', 'PHEV', 'suv', 'c', 2024, 'on_sale'),
-- Tesla (brand_id=2)
(2, 'Model 3', 'BEV', 'sedan', 'c', 2024, 'on_sale'),
(2, 'Model Y', 'BEV', 'suv', 'c', 2023, 'on_sale'),
-- MG (brand_id=3)
(3, 'MG4 Electric', 'BEV', 'hatchback', 'c', 2023, 'on_sale'),
(3, 'ZS EV', 'BEV', 'suv', 'b', 2022, 'on_sale'),
-- ORA (brand_id=4)
(4, 'Good Cat', 'BEV', 'hatchback', 'b', 2022, 'on_sale'),
-- Neta (brand_id=5)
(5, 'V-II', 'BEV', 'suv', 'b', 2023, 'on_sale'),
-- Toyota (brand_id=6)
(6, 'Yaris Cross', 'HEV', 'suv', 'b', 2023, 'on_sale'),
(6, 'bZ4X', 'BEV', 'suv', 'c', 2023, 'on_sale'),
-- Honda (brand_id=7)
(7, 'e:N1', 'BEV', 'suv', 'c', 2024, 'on_sale'),
-- Hyundai (brand_id=8)
(8, 'IONIQ 5', 'BEV', 'suv', 'c', 2022, 'on_sale'),
-- AION (brand_id=12)
(12, 'Y Plus', 'BEV', 'suv', 'b', 2023, 'on_sale');

-- VARIANTS (detailed specs)

-- 1. BYD Atto 3 Standard Range (model_id=1)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, ac_charge_time_hrs, dc_charge_time_mins, charging_port, v2l, heat_pump,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, ground_clearance_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, front_suspension, rear_suspension, front_brakes, rear_brakes, tire_size_front, spare_tire,
    airbags, abs, esc, traction_control, hill_start_assist, tpms, isofix,
    parking_sensor_front, parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, lka, ldw, bsd, rcta, acc, adas_level,
    ncap_rating, ncap_body, ncap_year,
    seats, seat_material, driver_seat_electric, ac_zones, rear_ac_vents,
    screen_size_inch, digital_cluster, cluster_size_inch, speaker_count,
    apple_carplay, android_auto, wireless_phone_charging, ota_update,
    headlight_type, drl, auto_headlights, sunroof, power_tailgate, keyless_entry, push_start, auto_folding_mirrors,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (1, 'Standard Range', 1099900, 'on_sale',
    49.92, 'LFP', 150, 310, 410, 'NEDC',
    7, 70, 8, 45, 'CCS2', FALSE, FALSE,
    160, 7.3,
    4455, 1875, 1615, 2720, 175, 1750, 440,
    'FWD', 'MacPherson Strut', 'Multi-link', 'Ventilated Disc', 'Disc', '235/50R18', 'Tire Repair Kit',
    7, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    FALSE, TRUE, TRUE, FALSE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'L2',
    5, 'ASEAN NCAP', 2023,
    5, 'Fabric/Leather', TRUE, 1, TRUE,
    12.8, TRUE, 5, 8,
    TRUE, TRUE, TRUE, TRUE,
    'LED', TRUE, TRUE, 'none', FALSE, TRUE, TRUE, TRUE,
    6, 150000, 8, 160000
);

-- 2. BYD Atto 3 Extended Range (model_id=1)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, ac_charge_time_hrs, dc_charge_time_mins, charging_port, v2l, heat_pump,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, ground_clearance_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, front_suspension, rear_suspension, front_brakes, rear_brakes, tire_size_front, spare_tire,
    airbags, abs, esc, traction_control, hill_start_assist, tpms, isofix,
    parking_sensor_front, parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, lka, ldw, bsd, rcta, acc, adas_level,
    ncap_rating, ncap_body, ncap_year,
    seats, seat_material, driver_seat_electric, ventilated_seats_front, ac_zones, rear_ac_vents,
    screen_size_inch, digital_cluster, cluster_size_inch, speaker_count,
    apple_carplay, android_auto, wireless_phone_charging, ota_update,
    headlight_type, drl, auto_headlights, sunroof, power_tailgate, keyless_entry, push_start, auto_folding_mirrors,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (1, 'Extended Range', 1299900, 'on_sale',
    60.48, 'LFP', 150, 310, 480, 'NEDC',
    7, 80, 9.5, 40, 'CCS2', FALSE, TRUE,
    160, 7.3,
    4455, 1875, 1615, 2720, 175, 1830, 440,
    'FWD', 'MacPherson Strut', 'Multi-link', 'Ventilated Disc', 'Disc', '235/50R18', 'Tire Repair Kit',
    7, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'L2',
    5, 'ASEAN NCAP', 2023,
    5, 'Leather', TRUE, TRUE, 2, TRUE,
    12.8, TRUE, 5, 8,
    TRUE, TRUE, TRUE, TRUE,
    'LED', TRUE, TRUE, 'panoramic', TRUE, TRUE, TRUE, TRUE,
    6, 150000, 8, 160000
);

-- 3. BYD Dolphin Standard Range (model_id=2)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, ac_charge_time_hrs, dc_charge_time_mins, charging_port, v2l, heat_pump,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, airbags, abs, esc, tpms, isofix,
    parking_sensor_rear, camera_rear,
    aeb, fcw, ldw, adas_level,
    seats, seat_material, ac_zones,
    screen_size_inch, digital_cluster, cluster_size_inch,
    apple_carplay, android_auto, wireless_phone_charging, ota_update,
    headlight_type, drl, keyless_entry, push_start,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (2, 'Standard Range', 699900, 'on_sale',
    44.9, 'LFP', 70, 180, 410, 'NEDC',
    7, 60, 7.5, 50, 'CCS2', FALSE, FALSE,
    150, 12.3,
    4290, 1770, 1570, 2700, 1520, 345,
    'FWD', 6, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE,
    TRUE, TRUE, TRUE, 'L1',
    5, 'Fabric', 1,
    12.8, TRUE, 5,
    TRUE, TRUE, TRUE, TRUE,
    'LED', TRUE, TRUE, TRUE,
    6, 150000, 8, 160000
);

-- 4. BYD Seal Dynamic (model_id=3)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port, v2l, heat_pump,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters, frunk_capacity_liters,
    drive_type, airbags, abs, esc, traction_control, hill_start_assist, tpms, isofix,
    parking_sensor_front, parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, lka, ldw, bsd, rcta, acc, acc_stop_go, adas_level,
    seats, seat_material, driver_seat_electric, ventilated_seats_front, ac_zones,
    screen_size_inch, digital_cluster, hud, speaker_count,
    apple_carplay, android_auto, wireless_phone_charging, ota_update,
    headlight_type, drl, auto_headlights, sunroof, power_tailgate, keyless_entry, push_start, auto_folding_mirrors,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (3, 'Dynamic', 1249900, 'on_sale',
    61.44, 'BYD Blade (LFP)', 150, 310, 460, 'NEDC',
    7, 110, 35, 'CCS2', FALSE, TRUE,
    180, 7.5,
    4800, 1875, 1460, 2920, 1885, 400, 50,
    'RWD', 7, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'L2',
    5, 'Leather', TRUE, TRUE, 2,
    15.6, TRUE, TRUE, 12,
    TRUE, TRUE, TRUE, TRUE,
    'LED', TRUE, TRUE, 'panoramic', TRUE, TRUE, TRUE, TRUE,
    6, 150000, 8, 160000
);

-- 5. BYD Sealion 6 DM-i Premium (model_id=4, PHEV)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, charging_port, ev_range_km,
    displacement_cc, engine_type, horsepower, engine_torque_nm, fuel_type, fuel_tank_liters, fuel_consumption_kml, turbo,
    transmission, system_power_hp, system_torque_nm,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, airbags, abs, esc, traction_control, tpms, isofix,
    parking_sensor_front, parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, lka, ldw, bsd, rcta, acc, acc_stop_go, adas_level,
    seats, seat_material, driver_seat_electric, ventilated_seats_front, ac_zones, rear_ac_vents,
    screen_size_inch, digital_cluster, hud, speaker_count,
    apple_carplay, android_auto, wireless_phone_charging, ota_update,
    headlight_type, drl, auto_headlights, sunroof, power_tailgate, keyless_entry, push_start, auto_folding_mirrors,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (4, 'Premium', 1099900, 'on_sale',
    18.3, 'LFP', 145, 325, NULL, NULL,
    3.3, 'Type 2', 92,
    1499, '1.5L Atkinson', 110, 135, 'gasoline_95', 65, 25, FALSE,
    'E-CVT', 218, 325,
    185, 7.9,
    4830, 1890, 1670, 2790, 1890, 425,
    'FWD', 7, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'L2',
    5, 'Leather', TRUE, TRUE, 2, TRUE,
    12.8, TRUE, TRUE, 8,
    TRUE, TRUE, TRUE, TRUE,
    'LED', TRUE, TRUE, 'panoramic', TRUE, TRUE, TRUE, TRUE,
    6, 150000, 8, 160000
);

-- 6. Tesla Model 3 RWD (model_id=5)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port, v2l, heat_pump,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters, frunk_capacity_liters,
    drive_type, airbags, abs, esc, traction_control, tpms, isofix,
    parking_sensor_front, parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, lka, ldw, bsd, acc, acc_stop_go, driver_monitoring, adas_level,
    ncap_rating, ncap_body, ncap_year,
    seats, seat_material, driver_seat_electric, heated_seats_front, heated_seats_rear, ac_zones,
    screen_size_inch, digital_cluster, speaker_count,
    wireless_phone_charging, ota_update, bluetooth,
    headlight_type, drl, auto_headlights, sunroof, keyless_entry, push_start, auto_folding_mirrors,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (5, 'RWD (Highland)', 1559900, 'on_sale',
    60, 'LFP', 208, 340, 513, 'WLTP',
    11, 170, 25, 'CCS2', FALSE, TRUE,
    201, 6.1,
    4720, 1849, 1441, 2875, 1761, 594, 88,
    'RWD', 8, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, FALSE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'Camera', 'L2',
    5, 'Euro NCAP', 2024,
    5, 'Vegan Leather', TRUE, TRUE, TRUE, 2,
    15.4, FALSE, 17,
    TRUE, TRUE, '5.3',
    'LED Matrix', TRUE, TRUE, 'glass_roof', TRUE, TRUE, TRUE,
    4, 80000, 8, 192000
);

-- 7. Tesla Model 3 Long Range AWD (model_id=5)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, front_motor_kw, rear_motor_kw, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port, v2l, heat_pump,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters, frunk_capacity_liters,
    drive_type, airbags, abs, esc, traction_control, tpms, isofix,
    parking_sensor_front, parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, lka, ldw, bsd, acc, acc_stop_go, driver_monitoring, adas_level,
    seats, seat_material, driver_seat_electric, heated_seats_front, heated_seats_rear, ac_zones,
    screen_size_inch, digital_cluster, speaker_count,
    wireless_phone_charging, ota_update, bluetooth,
    headlight_type, drl, auto_headlights, sunroof, keyless_entry, push_start, auto_folding_mirrors,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (5, 'Long Range AWD (Highland)', 1879900, 'on_sale',
    78.1, 'NMC', 366, 493, 137, 208, 678, 'WLTP',
    11, 250, 20, 'CCS2', FALSE, TRUE,
    201, 4.4,
    4720, 1849, 1441, 2875, 1828, 594, 88,
    'AWD', 8, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, FALSE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'Camera', 'L2',
    5, 'Vegan Leather', TRUE, TRUE, TRUE, 2,
    15.4, FALSE, 17,
    TRUE, TRUE, '5.3',
    'LED Matrix', TRUE, TRUE, 'glass_roof', TRUE, TRUE, TRUE,
    4, 80000, 8, 192000
);

-- 8. MG4 Electric Standard (model_id=7)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, airbags, abs, esc, traction_control, tpms, isofix,
    parking_sensor_rear, camera_rear,
    aeb, fcw, ldw, bsd, acc, adas_level,
    seats, seat_material, ac_zones,
    screen_size_inch, digital_cluster, cluster_size_inch,
    apple_carplay, android_auto, ota_update,
    headlight_type, drl, keyless_entry, push_start,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (7, 'Standard Range', 869900, 'on_sale',
    51, 'LFP', 125, 250, 350, 'WLTP',
    6.6, 87, 40, 'CCS2',
    160, 7.7,
    4287, 1836, 1504, 2705, 1655, 363,
    'RWD', 6, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, 'L2',
    5, 'Fabric/Leather', 1,
    10.25, TRUE, 7,
    TRUE, TRUE, TRUE,
    'LED', TRUE, TRUE, TRUE,
    5, 150000, 8, 180000
);

-- 9. Toyota Yaris Cross HEV Smart (model_id=11, HEV with engine specs)
INSERT INTO car_variants (model_id, name, price_baht, status,
    displacement_cc, engine_type, horsepower, engine_torque_nm, fuel_type, fuel_tank_liters, fuel_consumption_kml, turbo,
    transmission, system_power_hp, system_torque_nm,
    battery_capacity_kwh, motor_power_kw,
    top_speed_kmh,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, airbags, abs, esc, traction_control, hill_start_assist, tpms, isofix,
    parking_sensor_rear, camera_rear,
    aeb, fcw, lka, acc, adas_level,
    ncap_rating, ncap_body, ncap_year,
    seats, seat_material, ac_zones,
    screen_size_inch, digital_cluster,
    apple_carplay, android_auto,
    headlight_type, drl, auto_headlights, keyless_entry, push_start,
    warranty_years, warranty_km
) VALUES (11, 'Smart HEV', 789000, 'on_sale',
    1490, '1.5L Dynamic Force + THS II', 91, 120, 'gasoline_95', 36, 28, FALSE,
    'E-CVT', 116, NULL,
    0.76, 59,
    170,
    4180, 1765, 1590, 2560, 1170, 390,
    'FWD', 7, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, 'L2',
    5, 'ASEAN NCAP', 2023,
    5, 'Fabric', 1,
    9, TRUE,
    TRUE, TRUE,
    'LED', TRUE, TRUE, TRUE, TRUE,
    5, 150000
);

-- 10. Hyundai IONIQ 5 Long Range (model_id=14)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port, v2l, heat_pump,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters, frunk_capacity_liters,
    drive_type, airbags, abs, esc, traction_control, tpms, isofix,
    parking_sensor_front, parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, lka, ldw, bsd, rcta, acc, acc_stop_go, driver_monitoring, adas_level,
    ncap_rating, ncap_body, ncap_year,
    seats, seat_material, driver_seat_electric, ventilated_seats_front, heated_seats_front, ac_zones, rear_ac_vents,
    screen_size_inch, digital_cluster, cluster_size_inch, hud, speaker_brand, speaker_count,
    apple_carplay, android_auto, wireless_phone_charging, ota_update, bluetooth,
    headlight_type, drl, auto_headlights, sunroof, power_tailgate, keyless_entry, push_start, auto_folding_mirrors,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (14, 'Long Range RWD', 1799000, 'on_sale',
    77.4, 'NMC', 168, 350, 481, 'WLTP',
    11, 233, 18, 'CCS2', TRUE, TRUE,
    185, 7.4,
    4635, 1890, 1605, 3000, 1950, 527, 57,
    'RWD', 7, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'Camera', 'L2',
    5, 'Euro NCAP', 2022,
    5, 'Leather', TRUE, TRUE, TRUE, 2, TRUE,
    12.3, TRUE, 12.3, TRUE, 'BOSE', 8,
    TRUE, TRUE, TRUE, TRUE, '5.1',
    'LED', TRUE, TRUE, 'panoramic', TRUE, TRUE, TRUE, TRUE,
    5, 150000, 8, 160000
);

-- 11. ORA Good Cat 500 Ultra (model_id=9)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port,
    top_speed_kmh, acceleration_0_100,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, airbags, abs, esc, tpms, isofix,
    parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, ldw, adas_level,
    seats, seat_material, ac_zones,
    screen_size_inch, digital_cluster,
    apple_carplay, android_auto,
    headlight_type, drl, keyless_entry, push_start,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (9, '500 Ultra', 999900, 'on_sale',
    63.1, 105, 210, 500, 'NEDC',
    6.6, 63, 46, 'CCS2',
    152, 8.5,
    4235, 1825, 1596, 2650, 1555, 228,
    'FWD', 6, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, 'L1',
    5, 'Leather', 1,
    10.25, TRUE,
    TRUE, TRUE,
    'LED', TRUE, TRUE, TRUE,
    5, 150000, 8, 150000
);

-- 12. Neta V-II (model_id=10)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port,
    top_speed_kmh,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, airbags, abs, esc, tpms,
    parking_sensor_rear, camera_rear,
    aeb, adas_level,
    seats, seat_material, ac_zones,
    screen_size_inch, digital_cluster,
    apple_carplay, android_auto,
    headlight_type, drl, keyless_entry, push_start,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (10, 'Mid', 549900, 'on_sale',
    38.5, 70, 150, 381, 'NEDC',
    6.6, 48, 45, 'CCS2',
    120,
    4070, 1690, 1540, 2420, 1200, 335,
    'FWD', 4, TRUE, TRUE, TRUE,
    TRUE, TRUE,
    TRUE, 'L1',
    5, 'Fabric', 1,
    10, TRUE,
    TRUE, TRUE,
    'LED', TRUE, TRUE, TRUE,
    5, 150000, 8, 150000
);

-- 13. AION Y Plus 490 (model_id=15)
INSERT INTO car_variants (model_id, name, price_baht, status,
    battery_capacity_kwh, battery_type, motor_power_kw, motor_torque_nm, range_km, range_standard,
    ac_charge_kw, dc_charge_kw, dc_charge_time_mins, charging_port,
    top_speed_kmh,
    length_mm, width_mm, height_mm, wheelbase_mm, curb_weight_kg, trunk_capacity_liters,
    drive_type, airbags, abs, esc, tpms, isofix,
    parking_sensor_rear, camera_rear, camera_360,
    aeb, fcw, ldw, adas_level,
    seats, seat_material, driver_seat_electric, ac_zones,
    screen_size_inch, digital_cluster,
    apple_carplay, android_auto, wireless_phone_charging, ota_update,
    headlight_type, drl, keyless_entry, push_start,
    warranty_years, warranty_km, battery_warranty_years, battery_warranty_km
) VALUES (15, '490 Premium', 899900, 'on_sale',
    63.2, 'LFP', 150, 225, 490, 'NEDC',
    6.6, 80, 38, 'CCS2',
    150,
    4410, 1870, 1645, 2750, 1690, 476,
    'FWD', 6, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, 'L2',
    5, 'Leather', TRUE, 1,
    14.6, TRUE,
    TRUE, TRUE, TRUE, TRUE,
    'LED', TRUE, TRUE, TRUE,
    5, 150000, 8, 150000
);
